// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: schema.proto

package org.xproce.lab;

public interface CreatorOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.xproce.lab.Creator)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
