// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: schema.proto

package org.xproce.lab;

public interface UploadVideoRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.xproce.lab.UploadVideoRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string title = 1;</code>
   * @return The title.
   */
  java.lang.String getTitle();
  /**
   * <code>string title = 1;</code>
   * @return The bytes for title.
   */
  com.google.protobuf.ByteString
      getTitleBytes();

  /**
   * <code>.org.xproce.lab.Creator creator = 2;</code>
   * @return Whether the creator field is set.
   */
  boolean hasCreator();
  /**
   * <code>.org.xproce.lab.Creator creator = 2;</code>
   * @return The creator.
   */
  org.xproce.lab.Creator getCreator();
  /**
   * <code>.org.xproce.lab.Creator creator = 2;</code>
   */
  org.xproce.lab.CreatorOrBuilder getCreatorOrBuilder();
}
