// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: schema.proto

package org.xproce.lab;

public interface VideoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.xproce.lab.Video)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>.org.xproce.lab.Creator creator = 2;</code>
   * @return Whether the creator field is set.
   */
  boolean hasCreator();
  /**
   * <code>.org.xproce.lab.Creator creator = 2;</code>
   * @return The creator.
   */
  org.xproce.lab.Creator getCreator();
  /**
   * <code>.org.xproce.lab.Creator creator = 2;</code>
   */
  org.xproce.lab.CreatorOrBuilder getCreatorOrBuilder();
}
